#library(SummarizedExperiment)
library(Seurat)
library(dplyr)
# library(proxy)
library(data.table)
library(ggplot2)
#library(IRanges)
library(mixtools)
#library(GenomicRanges)
library(RColorBrewer)
# library(pheatmap)
# library(mixdist)
#library(Matrix)
# library(readxl)
# library(tibble)
# library(plyr)
# library(stringr)
# library(gplots)
# library(shiny)
#library(Hmisc)
library(ComplexHeatmap)
library(circlize)
library(viridis)
#library(cowplot)
#library(SeuratObject)
# library(pracma)
# library(ini)
#library(ape)


